name: Build Argon OpenWrt Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev \
            libssl-dev python3-setuptools rsync unzip zlib1g-dev file wget


      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/25.12.1/targets/ramips/mt7621/openwrt-sdk-25.12.1-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar --zstd -xf openwrt-sdk-*.tar.zst
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*" | head -n 1)
          mv "$SDK_DIR" sdk
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add packages
        run: |
          cd sdk/package
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          cd luci-theme-argon
          sed -i 's/LUCI_DEPENDS:=+wget/LUCI_DEPENDS:=+wget-ssl/' Makefile
          cd ..
          git clone https://github.com/jerrykuku/luci-app-argon-config.git


      - name: Configure
        run: |
          cd sdk
          cat <<EOF > .config
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          EOF
          make defconfig

      
      - name: Build
        run: |
          cd sdk
          make package/luci-theme-argon/compile V=s
          make package/luci-app-argon-config/compile V=s


      - name: Collect packages
        run: |
          mkdir -p output
          find sdk/bin/packages -type f \( -name "*.ipk" -o -name "*.apk" \) \
            | grep -E "luci-theme-argon|luci-app-argon-config" \
            | while read f; do
                echo "Found: $f"
                cp "$f" output/
              done

          echo "==== OUTPUT ===="
          ls -lh output || true


      - name: Extract version
        id: version
        run: |
          THEME_VER=$(grep PKG_VERSION sdk/package/luci-theme-argon/Makefile | cut -d= -f2)
          CONFIG_VER=$(grep PKG_VERSION sdk/package/luci-app-argon-config/Makefile | cut -d= -f2)

          echo "theme=$THEME_VER" >> $GITHUB_OUTPUT
          echo "config=$CONFIG_VER" >> $GITHUB_OUTPUT

      - name: Rename packages
        run: |
          cd output
          for f in *.ipk *.apk; do
            if [[ $f == *luci-theme-argon* ]]; then
              mv "$f" "luci-theme-argon-${{ steps.version.outputs.theme }}.${f##*.}"
            elif [[ $f == *luci-app-argon-config* ]]; then
              mv "$f" "luci-app-argon-config-${{ steps.version.outputs.config }}.${f##*.}"
            fi
          done


      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: argon-${{ steps.version.outputs.theme }}
          name: Argon ${{ steps.version.outputs.theme }}
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
